# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15UkgGlYN0HaEby4oNWND3tUFek-k1PoR
"""

import cv2
import numpy as np

img=cv2.imread("ISIC_0000214.jpg")
image=cv2.pyrDown(img)

gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
grad=cv2.Laplacian(gray,-1,ksize=5)

ret, binary=cv2.threshold(grad.copy(),100,255,cv2.THRESH_BINARY)
kernel=np.ones((3,3),np.uint8)
mask=cv2.dilate(binary.copy(),kernel,iterations=1)
restoreImage=cv2.inpaint(image,mask,17,cv2.INPAINT_TELEA)

cv2.imshow("ben",image)
cv2.imshow("maskem",grad)
cv2.imshow("son",restoreImage)
cv2.waitKey(0)